// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query.proto

package org.ioc.server.procol;

public final class QueryObject {
  private QueryObject() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface queryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 StartTimestamp = 1;
    /**
     * <code>required int64 StartTimestamp = 1;</code>
     */
    boolean hasStartTimestamp();
    /**
     * <code>required int64 StartTimestamp = 1;</code>
     */
    long getStartTimestamp();

    // required int64 EndTimestamp = 2;
    /**
     * <code>required int64 EndTimestamp = 2;</code>
     */
    boolean hasEndTimestamp();
    /**
     * <code>required int64 EndTimestamp = 2;</code>
     */
    long getEndTimestamp();

    // optional string uid = 3;
    /**
     * <code>optional string uid = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.  
     * </pre>
     */
    boolean hasUid();
    /**
     * <code>optional string uid = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.  
     * </pre>
     */
    java.lang.String getUid();
    /**
     * <code>optional string uid = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.  
     * </pre>
     */
    com.google.protobuf.ByteString
        getUidBytes();
  }
  /**
   * Protobuf type {@code query.query}
   */
  public static final class query extends
      com.google.protobuf.GeneratedMessage
      implements queryOrBuilder {
    // Use query.newBuilder() to construct.
    private query(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private query(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final query defaultInstance;
    public static query getDefaultInstance() {
      return defaultInstance;
    }

    public query getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private query(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              startTimestamp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              endTimestamp_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              uid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ioc.server.procol.QueryObject.internal_static_query_query_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ioc.server.procol.QueryObject.internal_static_query_query_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ioc.server.procol.QueryObject.query.class, org.ioc.server.procol.QueryObject.query.Builder.class);
    }

    public static com.google.protobuf.Parser<query> PARSER =
        new com.google.protobuf.AbstractParser<query>() {
      public query parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new query(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<query> getParserForType() {
      return PARSER;
    }

    public interface TargsOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string targt = 1;
      /**
       * <code>optional string targt = 1;</code>
       */
      boolean hasTargt();
      /**
       * <code>optional string targt = 1;</code>
       */
      java.lang.String getTargt();
      /**
       * <code>optional string targt = 1;</code>
       */
      com.google.protobuf.ByteString
          getTargtBytes();

      // optional string targv = 2;
      /**
       * <code>optional string targv = 2;</code>
       */
      boolean hasTargv();
      /**
       * <code>optional string targv = 2;</code>
       */
      java.lang.String getTargv();
      /**
       * <code>optional string targv = 2;</code>
       */
      com.google.protobuf.ByteString
          getTargvBytes();
    }
    /**
     * Protobuf type {@code query.query.Targs}
     */
    public static final class Targs extends
        com.google.protobuf.GeneratedMessage
        implements TargsOrBuilder {
      // Use Targs.newBuilder() to construct.
      private Targs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Targs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Targs defaultInstance;
      public static Targs getDefaultInstance() {
        return defaultInstance;
      }

      public Targs getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Targs(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                targt_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                targv_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ioc.server.procol.QueryObject.internal_static_query_query_Targs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ioc.server.procol.QueryObject.internal_static_query_query_Targs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ioc.server.procol.QueryObject.query.Targs.class, org.ioc.server.procol.QueryObject.query.Targs.Builder.class);
      }

      public static com.google.protobuf.Parser<Targs> PARSER =
          new com.google.protobuf.AbstractParser<Targs>() {
        public Targs parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Targs(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Targs> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string targt = 1;
      public static final int TARGT_FIELD_NUMBER = 1;
      private java.lang.Object targt_;
      /**
       * <code>optional string targt = 1;</code>
       */
      public boolean hasTargt() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string targt = 1;</code>
       */
      public java.lang.String getTargt() {
        java.lang.Object ref = targt_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targt_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string targt = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTargtBytes() {
        java.lang.Object ref = targt_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string targv = 2;
      public static final int TARGV_FIELD_NUMBER = 2;
      private java.lang.Object targv_;
      /**
       * <code>optional string targv = 2;</code>
       */
      public boolean hasTargv() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string targv = 2;</code>
       */
      public java.lang.String getTargv() {
        java.lang.Object ref = targv_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targv_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string targv = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTargvBytes() {
        java.lang.Object ref = targv_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targv_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        targt_ = "";
        targv_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTargtBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTargvBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTargtBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTargvBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.ioc.server.procol.QueryObject.query.Targs parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.ioc.server.procol.QueryObject.query.Targs parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.ioc.server.procol.QueryObject.query.Targs prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code query.query.Targs}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.ioc.server.procol.QueryObject.query.TargsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.ioc.server.procol.QueryObject.internal_static_query_query_Targs_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.ioc.server.procol.QueryObject.internal_static_query_query_Targs_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.ioc.server.procol.QueryObject.query.Targs.class, org.ioc.server.procol.QueryObject.query.Targs.Builder.class);
        }

        // Construct using org.ioc.server.procol.QueryServer.query.Targs.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          targt_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          targv_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.ioc.server.procol.QueryObject.internal_static_query_query_Targs_descriptor;
        }

        public org.ioc.server.procol.QueryObject.query.Targs getDefaultInstanceForType() {
          return org.ioc.server.procol.QueryObject.query.Targs.getDefaultInstance();
        }

        public org.ioc.server.procol.QueryObject.query.Targs build() {
          org.ioc.server.procol.QueryObject.query.Targs result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.ioc.server.procol.QueryObject.query.Targs buildPartial() {
          org.ioc.server.procol.QueryObject.query.Targs result = new org.ioc.server.procol.QueryObject.query.Targs(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.targt_ = targt_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.targv_ = targv_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.ioc.server.procol.QueryObject.query.Targs) {
            return mergeFrom((org.ioc.server.procol.QueryObject.query.Targs)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.ioc.server.procol.QueryObject.query.Targs other) {
          if (other == org.ioc.server.procol.QueryObject.query.Targs.getDefaultInstance()) return this;
          if (other.hasTargt()) {
            bitField0_ |= 0x00000001;
            targt_ = other.targt_;
            onChanged();
          }
          if (other.hasTargv()) {
            bitField0_ |= 0x00000002;
            targv_ = other.targv_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.ioc.server.procol.QueryObject.query.Targs parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.ioc.server.procol.QueryObject.query.Targs) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string targt = 1;
        private java.lang.Object targt_ = "";
        /**
         * <code>optional string targt = 1;</code>
         */
        public boolean hasTargt() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string targt = 1;</code>
         */
        public java.lang.String getTargt() {
          java.lang.Object ref = targt_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            targt_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string targt = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTargtBytes() {
          java.lang.Object ref = targt_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            targt_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string targt = 1;</code>
         */
        public Builder setTargt(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          targt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string targt = 1;</code>
         */
        public Builder clearTargt() {
          bitField0_ = (bitField0_ & ~0x00000001);
          targt_ = getDefaultInstance().getTargt();
          onChanged();
          return this;
        }
        /**
         * <code>optional string targt = 1;</code>
         */
        public Builder setTargtBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          targt_ = value;
          onChanged();
          return this;
        }

        // optional string targv = 2;
        private java.lang.Object targv_ = "";
        /**
         * <code>optional string targv = 2;</code>
         */
        public boolean hasTargv() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string targv = 2;</code>
         */
        public java.lang.String getTargv() {
          java.lang.Object ref = targv_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            targv_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string targv = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTargvBytes() {
          java.lang.Object ref = targv_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            targv_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string targv = 2;</code>
         */
        public Builder setTargv(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          targv_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string targv = 2;</code>
         */
        public Builder clearTargv() {
          bitField0_ = (bitField0_ & ~0x00000002);
          targv_ = getDefaultInstance().getTargv();
          onChanged();
          return this;
        }
        /**
         * <code>optional string targv = 2;</code>
         */
        public Builder setTargvBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          targv_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:query.query.Targs)
      }

      static {
        defaultInstance = new Targs(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:query.query.Targs)
    }

    private int bitField0_;
    // required int64 StartTimestamp = 1;
    public static final int STARTTIMESTAMP_FIELD_NUMBER = 1;
    private long startTimestamp_;
    /**
     * <code>required int64 StartTimestamp = 1;</code>
     */
    public boolean hasStartTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 StartTimestamp = 1;</code>
     */
    public long getStartTimestamp() {
      return startTimestamp_;
    }

    // required int64 EndTimestamp = 2;
    public static final int ENDTIMESTAMP_FIELD_NUMBER = 2;
    private long endTimestamp_;
    /**
     * <code>required int64 EndTimestamp = 2;</code>
     */
    public boolean hasEndTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 EndTimestamp = 2;</code>
     */
    public long getEndTimestamp() {
      return endTimestamp_;
    }

    // optional string uid = 3;
    public static final int UID_FIELD_NUMBER = 3;
    private java.lang.Object uid_;
    /**
     * <code>optional string uid = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.  
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string uid = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.  
     * </pre>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uid = 3;</code>
     *
     * <pre>
     * Unique ID number for this person.  
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      startTimestamp_ = 0L;
      endTimestamp_ = 0L;
      uid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStartTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, startTimestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, endTimestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUidBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, startTimestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, endTimestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.ioc.server.procol.QueryObject.query parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ioc.server.procol.QueryObject.query parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ioc.server.procol.QueryObject.query parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ioc.server.procol.QueryObject.query parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ioc.server.procol.QueryObject.query parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.ioc.server.procol.QueryObject.query parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.ioc.server.procol.QueryObject.query parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.ioc.server.procol.QueryObject.query parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.ioc.server.procol.QueryObject.query parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.ioc.server.procol.QueryObject.query parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.ioc.server.procol.QueryObject.query prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code query.query}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.ioc.server.procol.QueryObject.queryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ioc.server.procol.QueryObject.internal_static_query_query_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ioc.server.procol.QueryObject.internal_static_query_query_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ioc.server.procol.QueryObject.query.class, org.ioc.server.procol.QueryObject.query.Builder.class);
      }

      // Construct using org.ioc.server.procol.QueryServer.query.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        startTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        endTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ioc.server.procol.QueryObject.internal_static_query_query_descriptor;
      }

      public org.ioc.server.procol.QueryObject.query getDefaultInstanceForType() {
        return org.ioc.server.procol.QueryObject.query.getDefaultInstance();
      }

      public org.ioc.server.procol.QueryObject.query build() {
        org.ioc.server.procol.QueryObject.query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.ioc.server.procol.QueryObject.query buildPartial() {
        org.ioc.server.procol.QueryObject.query result = new org.ioc.server.procol.QueryObject.query(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startTimestamp_ = startTimestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endTimestamp_ = endTimestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uid_ = uid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ioc.server.procol.QueryObject.query) {
          return mergeFrom((org.ioc.server.procol.QueryObject.query)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ioc.server.procol.QueryObject.query other) {
        if (other == org.ioc.server.procol.QueryObject.query.getDefaultInstance()) return this;
        if (other.hasStartTimestamp()) {
          setStartTimestamp(other.getStartTimestamp());
        }
        if (other.hasEndTimestamp()) {
          setEndTimestamp(other.getEndTimestamp());
        }
        if (other.hasUid()) {
          bitField0_ |= 0x00000004;
          uid_ = other.uid_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStartTimestamp()) {
          
          return false;
        }
        if (!hasEndTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ioc.server.procol.QueryObject.query parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ioc.server.procol.QueryObject.query) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 StartTimestamp = 1;
      private long startTimestamp_ ;
      /**
       * <code>required int64 StartTimestamp = 1;</code>
       */
      public boolean hasStartTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 StartTimestamp = 1;</code>
       */
      public long getStartTimestamp() {
        return startTimestamp_;
      }
      /**
       * <code>required int64 StartTimestamp = 1;</code>
       */
      public Builder setStartTimestamp(long value) {
        bitField0_ |= 0x00000001;
        startTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 StartTimestamp = 1;</code>
       */
      public Builder clearStartTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // required int64 EndTimestamp = 2;
      private long endTimestamp_ ;
      /**
       * <code>required int64 EndTimestamp = 2;</code>
       */
      public boolean hasEndTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 EndTimestamp = 2;</code>
       */
      public long getEndTimestamp() {
        return endTimestamp_;
      }
      /**
       * <code>required int64 EndTimestamp = 2;</code>
       */
      public Builder setEndTimestamp(long value) {
        bitField0_ |= 0x00000002;
        endTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 EndTimestamp = 2;</code>
       */
      public Builder clearEndTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional string uid = 3;
      private java.lang.Object uid_ = "";
      /**
       * <code>optional string uid = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.  
       * </pre>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string uid = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.  
       * </pre>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uid = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.  
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uid = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.  
       * </pre>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.  
       * </pre>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid = 3;</code>
       *
       * <pre>
       * Unique ID number for this person.  
       * </pre>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uid_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:query.query)
    }

    static {
      defaultInstance = new query(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:query.query)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_query_query_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_query_query_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_query_query_Targs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_query_query_Targs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013query.proto\022\005query\"i\n\005query\022\026\n\016StartTi" +
      "mestamp\030\001 \002(\003\022\024\n\014EndTimestamp\030\002 \002(\003\022\013\n\003u" +
      "id\030\003 \001(\t\032%\n\005Targs\022\r\n\005targt\030\001 \001(\t\022\r\n\005targ" +
      "v\030\002 \001(\tB$\n\025org.ioc.server.procolB\013QueryS" +
      "erver"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_query_query_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_query_query_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_query_query_descriptor,
              new java.lang.String[] { "StartTimestamp", "EndTimestamp", "Uid", });
          internal_static_query_query_Targs_descriptor =
            internal_static_query_query_descriptor.getNestedTypes().get(0);
          internal_static_query_query_Targs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_query_query_Targs_descriptor,
              new java.lang.String[] { "Targt", "Targv", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
